-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 25, 2021 at 12:19 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `labspot`
--

-- --------------------------------------------------------

--
-- Table structure for table `test_details`
--

CREATE TABLE `test_details` (
  `id` int(5) NOT NULL,
  `lab_name` varchar(50) NOT NULL,
  `lab_email` varchar(50) NOT NULL,
  `lab_test_name` varchar(50) NOT NULL,
  `lab_test_description` varchar(500) NOT NULL,
  `lab_test_price` varchar(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `test_details`
--

INSERT INTO `test_details` (`id`, `lab_name`, `lab_email`, `lab_test_name`, `lab_test_description`, `lab_test_price`) VALUES
(1, 'Envitro Laboratories Pvt Ltd', 'envitrolab@yopmail.com', 'Starch and Sugar test-Benedict\'s Solution', 'There are many types of carbohydrates. Benedict\'s solution is used to test for simple sugars, such as glucose. It is a clear blue solution of sodium and copper salts. In the presence of simple sugars, the blue solution changes color to green, yellow, and brick-red, depending on the amount of sugar.', '1500'),
(2, 'Envitro Laboratories Pvt Ltd', 'envitrolab@yopmail.com', 'Protein - Biuret solution', 'Proteins are needed for the growth and repair of our body.  Test if a food item contains protein Biuret solution is used to identify the presence of protein. Biuret reagent is a blue solution that, when it reacts with protein, will change color to pink-purple.', '1800'),
(3, 'Envitro Laboratories Pvt Ltd', 'envitrolab@yopmail.com', 'Fat - Sudan III stain', 'Fats are a fundamental part of our diet and are important for good health. They are the major source of energy and aids our body in absorbing fat-soluble vitamins. Sudan III is used to identify the presence of lipids in liquids. It will stain fat cells red.', '1700'),
(4, 'Envitro Laboratories Pvt Ltd', 'envitrolab@yopmail.com', 'Vitamin C', 'P1010 can be used to detect vitamin C in food. Vitamin C Reagent indicator solution is blue. A colorless end point will be reached when a solution containing vitamin C (such as orange juice) is added to this indicator.', '2000'),
(5, 'Food research laboratory', 'foodresearchlab@yopmail.com', 'Starch and Sugar test-Benedict\'s solution', 'There are many types of carbohydrates. Benedict\'s solution is used to test for simple sugars, such as glucose. It is a clear blue solution of sodium and copper salts. In the presence of simple sugars, the blue solution changes color to green, yellow ,and brick-red, depending on the amount of sugar.', '1600'),
(6, 'Food research laboratory', 'foodresearchlab@yopmail.com', 'Protein - Biuret solution', 'Proteins are needed for the growth and repair of our body.  Test if a food item contains protein Biuret solution is used to identify the presence of protein. Biuret reagent is a blue solution that, when it reacts with protein, will change color to pink-purple.', '1900'),
(7, 'Food research laboratory', 'foodresearchlab@yopmail.com', 'Fat - Sudan III stain', 'Fats are a fundamental part of our diet and are important for good health. They are the major source of energy and aids our body in absorbing fat-soluble vitamins. Sudan III is used to identify the presence of lipids in liquids. It will stain fat cells red.', '1800'),
(8, 'Food research laboratory', 'foodresearchlab@yopmail.com', 'Vitamin C', 'P1010 can be used to detect vitamin C in food. Vitamin C Reagent indicator solution is blue. A colorless end point will be reached when a solution containing vitamin C (such as orange juice) is added to this indicator.', '2100'),
(9, 'Baroda Analytical Services', 'barodaanalyticallab@yopmail.com', 'Starch and Sugar test-Benedict\'s solution', 'There are many types of carbohydrates. Benedict\'s solution is used to test for simple sugars, such as glucose. It is a clear blue solution of sodium and copper salts. In the presence of simple sugars, the blue solution changes color to green, yellow, and brick-red, depending on the amount of sugar.', '1700'),
(10, 'Baroda Analytical Services', 'barodaanalyticallab@yopmail.com', 'Protein - Biuret solution', 'Proteins are needed for the growth and repair of our body.  Test if a food item contains protein Biuret solution is used to identify the presence of protein. Biuret reagent is a blue solution that, when it reacts with protein, will change color to pink-purple.', '2000'),
(11, 'Baroda Analytical Services', 'barodaanalyticallab@yopmail.com', 'Fat - Sudan III stain', 'Fats are a fundamental part of our diet and are important for good health. They are the major source of energy and aids our body in absorbing fat-soluble vitamins. Sudan III is used to identify the presence of lipids in liquids. It will stain fat cells red.', '1900'),
(12, 'Baroda Analytical Services', 'barodaanalyticallab@yopmail.com', 'Vitamin C', 'P1010 can be used to detect vitamin C in food. Vitamin C Reagent indicator solution is blue. A colorless end point will be reached when a solution containing vitamin C (such as orange juice) is added to this indicator.', '2200'),
(13, 'Pollucon Laboratories Private Limited', 'polluconlab@yopmail.com', 'Starch and Sugar test-Benedict\'s solution', 'There are many types of carbohydrates. Benedict\'s solution is used to test for simple sugars, such as glucose. It is a clear blue solution of sodium and copper salts. In the presence of simple sugars, the blue solution changes color to green, yellow, and brick-red, depending on the amount of sugar.', '1800'),
(14, 'Pollucon Laboratories Private Limited', 'polluconlab@yopmail.com', 'Protein - Biuret solution', 'Proteins are needed for the growth and repair of our body.  Test if a food item contains protein Biuret solution is used to identify the presence of protein. Biuret reagent is a blue solution that, when it reacts with protein, will change color to pink-purple.', '2100'),
(15, 'Pollucon Laboratories Private Limited', 'polluconlab@yopmail.com', 'Fat - Sudan III stain', 'Fats are a fundamental part of our diet and are important for good health. They are the major source of energy and aids our body in absorbing fat-soluble vitamins. Sudan III is used to identify the presence of lipids in liquids. It will stain fat cells red.', '2000'),
(16, 'Pollucon Laboratories Private Limited', 'polluconlab@yopmail.com', 'Vitamin C', 'P1010 can be used to detect vitamin C in food. Vitamin C Reagent indicator solution is blue. A colorless end point will be reached when a solution containing vitamin C (such as orange juice) is added to this indicator.', '2300'),
(17, 'Accurate Laboratory', 'accuratelab@yopmail.com', 'Starch and Sugar test-Benedict\'s solution', 'There are many types of carbohydrates. Benedict\'s solution is used to test for simple sugars, such as glucose. It is a clear blue solution of sodium and copper salts. In the presence of simple sugars, the blue solution changes color to green, yellow, and brick-red, depending on the amount of sugar.', '1900'),
(18, 'Accurate Laboratory', 'accuratelab@yopmail.com', 'Protein - Biuret solution', 'Proteins are needed for the growth and repair of our body.  Test if a food item contains protein Biuret solution is used to identify the presence of protein. Biuret reagent is a blue solution that, when it reacts with protein, will change color to pink-purple.', '2200'),
(19, 'Accurate Laboratory', 'accuratelab@yopmail.com', 'Fat - Sudan III stain', 'Fats are a fundamental part of our diet and are important for good health. They are the major source of energy and aids our body in absorbing fat-soluble vitamins. Sudan III is used to identify the presence of lipids in liquids. It will stain fat cells red.', '2100'),
(20, 'Accurate Laboratory', 'accuratelab@yopmail.com', 'Vitamin C', 'P1010 can be used to detect vitamin C in food. Vitamin C Reagent indicator solution is blue. A colorless end point will be reached when a solution containing vitamin C (such as orange juice) is added to this indicator.', '2400'),
(21, 'Krishna Water Testing Centre', 'krishnawatertestinglab@yopmail.com', 'Bacteria Tests', 'There are a range of potential bacterial contaminants that can plague water. One of the most common and most looked for is E. coli bacteria, which comes from fecal matter exposure and can result in serious health issues when consumed. Bacteria testing is essential in determining how safe water is to drink or expose to your skin.', '1700'),
(22, 'Krishna Water Testing Centre', 'krishnawatertestinglab@yopmail.com', 'Mineral Tests', 'The list of mineral testing available could be a these is paper, for how many there are. A few important mineral tests include chlorine and chloride, nitrate and nitrite, lead, copper, iron, zinc, potassium, sodium. This wide range of mineral testing is essential and relevant in determining water quality, as different regions or areas of terrain may have more of a buildup of certain types of minerals, which informs what kind of mineral treatments the water actually needs in order to be purified.', '2000'),
(23, 'Krishna Water Testing Centre', 'krishnawatertestinglab@yopmail.com', 'pH Testing', 'pH is a measure of the concentration of hydrogen ions in a solution. The more of these hydrogen ions there are in a solution, the more acidic that water is. Acidity effects taste of water, but it can also affect how health water is to consume. Drinking water that’s not neutral enough in acidity can make people sick.', '1900'),
(24, 'Krishna Water Testing Centre', 'krishnawatertestinglab@yopmail.com', 'Organic chemicals tests', 'It generally performed only if there is reason to believe a specific contaminant has infiltrated the water system (such as pesticides entering the water supply). Industrial and petroleum contamination can also be found through organic chemical testing.', '1500'),
(25, 'GEMI\'s Laboratory', 'gemilab@yopmail.com', 'Bacteria Tests', 'There are a range of potential bacterial contaminants that can plague water. One of the most common and most looked for is E. coli bacteria, which comes from fecal matter exposure and can result in serious health issues when consumed. Bacteria testing is essential in determining how safe water is to drink or expose to your skin.', '1800'),
(26, 'GEMI\'s Laboratory', 'gemilab@yopmail.com', 'Mineral Tests', 'The list of mineral testing available could be a these is paper, for how many there are. A few important mineral tests include chlorine and chloride, nitrate and nitrite, lead, copper, iron, zinc, potassium, sodium. This wide range of mineral testing is essential and relevant in determining water quality, as different regions or areas of terrain may have more of a buildup of certain types of minerals, which informs what kind of mineral treatments the water actually needs in order to be purified.', '2100'),
(27, 'GEMI\'s Laboratory', 'gemilab@yopmail.com', 'pH Testing', 'pH is a measure of the concentration of hydrogen ions in a solution. The more of these hydrogen ions there are in a solution, the more acidic that water is. Acidity effects taste of water, but it can also affect how health water is to consume. Drinking water that’s not neutral enough in acidity can make people sick.', '2000'),
(28, 'GEMI\'s Laboratory', 'gemilab@yopmail.com', 'Organic chemicals tests', 'It generally performed only if there is reason to believe a specific contaminant has infiltrated the water system (such as pesticides entering the water supply). Industrial and petroleum contamination can also be found through organic chemical testing.', '1600'),
(29, 'Analytical & Environmental Services', 'analyticalenvironmentlab@yopmail.com', 'Bacteria Tests', 'There are a range of potential bacterial contaminants that can plague water. One of the most common and most looked for is E. coli bacteria, which comes from fecal matter exposure and can result in serious health issues when consumed. Bacteria testing is essential in determining how safe water is to drink or expose to your skin.', '1900'),
(30, 'Analytical & Environmental Services', 'analyticalenvironmentlab@yopmail.com', 'Mineral Tests', 'The list of mineral testing available could be a these is paper, for how many there are. A few important mineral tests include chlorine and chloride, nitrate and nitrite, lead, copper, iron, zinc, potassium, sodium. This wide range of mineral testing is essential and relevant in determining water quality, as different regions or areas of terrain may have more of a buildup of certain types of minerals, which informs what kind of mineral treatments the water actually needs in order to be purified.', '2200'),
(31, 'Analytical & Environmental Services', 'analyticalenvironmentlab@yopmail.com', 'pH Testing', 'pH is a measure of the concentration of hydrogen ions in a solution. The more of these hydrogen ions there are in a solution, the more acidic that water is. Acidity effects taste of water, but it can also affect how health water is to consume. Drinking water that’s not neutral enough in acidity can make people sick.', '2100'),
(32, 'Analytical & Environmental Services', 'analyticalenvironmentlab@yopmail.com', 'Organic chemicals tests', 'It generally performed only if there is reason to believe a specific contaminant has infiltrated the water system (such as pesticides entering the water supply). Industrial and petroleum contamination can also be found through organic chemical testing.', '1700'),
(33, 'Stic Lab', 'sticlab@yopmail.com', 'Bacteria Tests', 'There are a range of potential bacterial contaminants that can plague water. One of the most common and most looked for is E. coli bacteria, which comes from fecal matter exposure and can result in serious health issues when consumed. Bacteria testing is essential in determining how safe water is to drink or expose to your skin.', '2000'),
(34, 'Stic Lab', 'sticlab@yopmail.com', 'Mineral Tests', 'The list of mineral testing available could be a these is paper, for how many there are. A few important mineral tests include chlorine and chloride, nitrate and nitrite, lead, copper, iron, zinc, potassium, sodium. This wide range of mineral testing is essential and relevant in determining water quality, as different regions or areas of terrain may have more of a buildup of certain types of minerals, which informs what kind of mineral treatments the water actually needs in order to be purified.', '2300'),
(35, 'Stic Lab', 'sticlab@yopmail.com', 'pH Testing', 'pH is a measure of the concentration of hydrogen ions in a solution. The more of these hydrogen ions there are in a solution, the more acidic that water is. Acidity effects taste of water, but it can also affect how health water is to consume. Drinking water that’s not neutral enough in acidity can make people sick.', '2200'),
(36, 'Stic Lab', 'sticlab@yopmail.com', 'Organic chemicals tests', 'It generally performed only if there is reason to believe a specific contaminant has infiltrated the water system (such as pesticides entering the water supply). Industrial and petroleum contamination can also be found through organic chemical testing.', '1800'),
(37, 'Biocare Research (India) Pvt Ltd', 'biocarelab@yopmail.com', 'Bacteria Tests', 'There are a range of potential bacterial contaminants that can plague water. One of the most common and most looked for is E. coli bacteria, which comes from fecal matter exposure and can result in serious health issues when consumed. Bacteria testing is essential in determining how safe water is to drink or expose to your skin.', '2100'),
(38, 'Biocare Research (India) Pvt Ltd', 'biocarelab@yopmail.com', 'Mineral Tests', 'The list of mineral testing available could be a these is paper, for how many there are. A few important mineral tests include chlorine and chloride, nitrate and nitrite, lead, copper, iron, zinc, potassium, sodium. This wide range of mineral testing is essential and relevant in determining water quality, as different regions or areas of terrain may have more of a buildup of certain types of minerals, which informs what kind of mineral treatments the water actually needs in order to be purified.', '2400'),
(39, 'Biocare Research (India) Pvt Ltd', 'biocarelab@yopmail.com', 'pH Testing', 'pH is a measure of the concentration of hydrogen ions in a solution. The more of these hydrogen ions there are in a solution, the more acidic that water is. Acidity effects taste of water, but it can also affect how health water is to consume. Drinking water that’s not neutral enough in acidity can make people sick.', '2300'),
(40, 'Biocare Research (India) Pvt Ltd', 'biocarelab@yopmail.com', 'Organic chemicals tests', 'It generally performed only if there is reason to believe a specific contaminant has infiltrated the water system (such as pesticides entering the water supply). Industrial and petroleum contamination can also be found through organic chemical testing.', '1900'),
(41, 'Bios Lab Private Limited', 'bioslab@yopmail.com', 'Drug Testing', 'A drug test looks for the presence of one or more illegal or prescription drugs in your urine, blood, saliva, hair, or sweat. Urine testing is the most common type of drug screening.', '2000'),
(42, 'Bios Lab Private Limited', 'bioslab@yopmail.com', 'Sterility Testing', 'Sterility testing is a key GMP Microbiology testing requirement for sterile pharmaceuticals, medical devices and materials, to ensure they are safe for use.', '1800'),
(43, 'Bios Lab Private Limited', 'bioslab@yopmail.com', 'Antimicrobial Efficacy Testing (AET)', 'We can perform antimicrobial effectiveness testing (AET or PET) to Ph. Eur. and USP on an array of products. The product is inoculated with a specified number of each challenge organism. Over a period of 28 days the product is examined to determine the number of viable microorganisms which survive at each specified time interval.', '2100'),
(44, 'Bios Lab Private Limited', 'bioslab@yopmail.com', 'Endotoxin (LAL) Testing', 'We can perform analysis of endotoxins using Kinetic Turbidimetric methodology. Limulus Amoebocyte Lysate (LAL) is used to detect and quantify bacterial endotoxins extracted from the products.', '1500'),
(45, 'Pharmace Research Laboratory', 'pharmaceresearchlab@yopmail.com', 'Drug Testing', 'A drug test looks for the presence of one or more illegal or prescription drugs in your urine, blood, saliva, hair, or sweat. Urine testing is the most common type of drug screening.', '2100'),
(46, 'Pharmace Research Laboratory', 'pharmaceresearchlab@yopmail.com', 'Sterility Testing', 'Sterility testing is a key GMP Microbiology testing requirement for sterile pharmaceuticals, medical devices and materials, to ensure they are safe for use.', '1900'),
(47, 'Pharmace Research Laboratory', 'pharmaceresearchlab@yopmail.com', 'Antimicrobial Efficacy Testing (AET)', 'We can perform antimicrobial effectiveness testing (AET or PET) to Ph. Eur. and USP on an array of products. The product is inoculated with a specified number of each challenge organism. Over a period of 28 days the product is examined to determine the number of viable microorganisms which survive at each specified time interval.', '2200'),
(48, 'Pharmace Research Laboratory', 'pharmaceresearchlab@yopmail.com', 'Endotoxin (LAL) Testing', 'We can perform analysis of endotoxins using Kinetic Turbidimetric methodology. Limulus Amoebocyte Lysate (LAL) is used to detect and quantify bacterial endotoxins extracted from the products.', '1600'),
(49, 'Shaimil Laboratories', 'shaimillab@yopmail.com', 'Drug Testing', 'A drug test looks for the presence of one or more illegal or prescription drugs in your urine, blood, saliva, hair, or sweat. Urine testing is the most common type of drug screening.', '2200'),
(50, 'Shaimil Laboratories', 'shaimillab@yopmail.com', 'Sterility Testing', 'Sterility testing is a key GMP Microbiology testing requirement for sterile pharmaceuticals, medical devices and materials, to ensure they are safe for use.', '2000'),
(51, 'Shaimil Laboratories', 'shaimillab@yopmail.com', 'Antimicrobial Efficacy Testing (AET)', 'We can perform antimicrobial effectiveness testing (AET or PET) to Ph. Eur. and USP on an array of products. The product is inoculated with a specified number of each challenge organism. Over a period of 28 days the product is examined to determine the number of viable microorganisms which survive at each specified time interval.', '2300'),
(52, 'Shaimil Laboratories', 'shaimillab@yopmail.com', 'Endotoxin (LAL) Testing', 'We can perform analysis of endotoxins using Kinetic Turbidimetric methodology. Limulus Amoebocyte Lysate (LAL) is used to detect and quantify bacterial endotoxins extracted from the products.', '1700'),
(53, 'K.L.M Laboratories Private Limited', 'klmlab@yopmail.com', 'Drug Testing', 'A drug test looks for the presence of one or more illegal or prescription drugs in your urine, blood, saliva, hair, or sweat. Urine testing is the most common type of drug screening.', '2300'),
(54, 'K.L.M Laboratories Private Limited', 'klmlab@yopmail.com', 'Sterility Testing', 'Sterility testing is a key GMP Microbiology testing requirement for sterile pharmaceuticals, medical devices and materials, to ensure they are safe for use.', '2100'),
(55, 'K.L.M Laboratories Private Limited', 'klmlab@yopmail.com', 'Antimicrobial Efficacy Testing (AET)', 'We can perform antimicrobial effectiveness testing (AET or PET) to Ph. Eur. and USP on an array of products. The product is inoculated with a specified number of each challenge organism. Over a period of 28 days the product is examined to determine the number of viable microorganisms which survive at each specified time interval.', '2400'),
(56, 'K.L.M Laboratories Private Limited', 'klmlab@yopmail.com', 'Endotoxin (LAL) Testing', 'We can perform analysis of endotoxins using Kinetic Turbidimetric methodology. Limulus Amoebocyte Lysate (LAL) is used to detect and quantify bacterial endotoxins extracted from the products.', '1800'),
(57, 'Gujarat Laboratory', 'gujaratlab@yopmail.com', 'Drug Testing', 'A drug test looks for the presence of one or more illegal or prescription drugs in your urine, blood, saliva, hair, or sweat. Urine testing is the most common type of drug screening.', '2400'),
(58, 'Gujarat Laboratory', 'gujaratlab@yopmail.com', 'Sterility Testing', 'Sterility testing is a key GMP Microbiology testing requirement for sterile pharmaceuticals, medical devices and materials, to ensure they are safe for use.', '2200'),
(59, 'Gujarat Laboratory', 'gujaratlab@yopmail.com', 'Antimicrobial Efficacy Testing (AET)', 'We can perform antimicrobial effectiveness testing (AET or PET) to Ph. Eur. and USP on an array of products. The product is inoculated with a specified number of each challenge organism. Over a period of 28 days the product is examined to determine the number of viable microorganisms which survive at each specified time interval.', '2500'),
(60, 'Gujarat Laboratory', 'gujaratlab@yopmail.com', 'Endotoxin (LAL) Testing', 'We can perform analysis of endotoxins using Kinetic Turbidimetric methodology. Limulus Amoebocyte Lysate (LAL) is used to detect and quantify bacterial endotoxins extracted from the products.', '1900'),
(61, 'Botany Desk', 'botanydesklab@yopmail.com', 'Seeds Purity Test', 'This test is useful in determining the physical purity of seed. A composite sample which is true representative of a seed lot is used for seed testing purpose. From the composite sample, a small sample known as working sample (generally 25 g) is drawn for testing purpose. International Seed Testing Association (ISTA) rules are adopted for seed testing.', '2600'),
(62, 'Botany Desk', 'botanydesklab@yopmail.com', 'Leaves Testing', 'Iodine solution is used to test leaves for the presence of starch. Add the leaf to boiling ethanol in a water bath for a few minutes (the boiling ethanol dissolves the chlorophyll and removes the green colour from the leaf - it turns white so it is easy to see the change in colour).', '2400'),
(63, 'Botany Desk', 'botanydesklab@yopmail.com', 'Flowers Testing', 'The flowering plants (also called angiosperms) are the dominant and most familiar group of land plants. The flowering plants and the gymnosperms comprise the two groups in the seed plants. The flowers of flowering plants are the most remarkable feature that distinguishes them from other seed plants.', '2500'),
(64, 'Botany Desk', 'botanydesklab@yopmail.com', 'Botany Cell Biology test', 'A large part of Cell Biology is the study of how biological molecules (mainly proteins and nucleic acids like DNA) account for the structure and function of cells.', '2100'),
(65, 'Plants Science  Laboratory', 'plantsciencelab@yopmail.com', 'Seeds Purity Test', 'This test is useful in determining the physical purity of seed. A composite sample which is true representative of a seed lot is used for seed testing purpose. From the composite sample, a small sample known as working sample (generally 25 g) is drawn for testing purpose. International Seed Testing Association (ISTA) rules are adopted for seed testing.', '2700'),
(66, 'Plants Science  Laboratory', 'plantsciencelab@yopmail.com', 'Leaves Testing', 'Iodine solution is used to test leaves for the presence of starch. Add the leaf to boiling ethanol in a water bath for a few minutes (the boiling ethanol dissolves the chlorophyll and removes the green colour from the leaf - it turns white so it is easy to see the change in colour).', '2400'),
(67, 'Plants Science  Laboratory', 'plantsciencelab@yopmail.com', 'Flowers Testing', 'The flowering plants (also called angiosperms) are the dominant and most familiar group of land plants. The flowering plants and the gymnosperms comprise the two groups in the seed plants. The flowers of flowering plants are the most remarkable feature that distinguishes them from other seed plants.', '2600'),
(68, 'Plants Science  Laboratory', 'plantsciencelab@yopmail.com', 'Botany Cell Biology test', 'A large part of Cell Biology is the study of how biological molecules (mainly proteins and nucleic acids like DNA) account for the structure and function of cells.', '2200'),
(69, 'Biacroft Lab', 'biacroftlab@yopmail.com', 'Seeds Purity Test', 'This test is useful in determining the physical purity of seed. A composite sample which is true representative of a seed lot is used for seed testing purpose. From the composite sample, a small sample known as working sample (generally 25 g) is drawn for testing purpose. International Seed Testing Association (ISTA) rules are adopted for seed testing.', '2800'),
(70, 'Biacroft Lab', 'biacroftlab@yopmail.com', 'Leaves Testing', 'Iodine solution is used to test leaves for the presence of starch. Add the leaf to boiling ethanol in a water bath for a few minutes (the boiling ethanol dissolves the chlorophyll and removes the green colour from the leaf - it turns white so it is easy to see the change in colour).', '2600'),
(71, 'Biacroft Lab', 'biacroftlab@yopmail.com', 'Flowers Testing', 'The flowering plants (also called angiosperms) are the dominant and most familiar group of land plants. The flowering plants and the gymnosperms comprise the two groups in the seed plants. The flowers of flowering plants are the most remarkable feature that distinguishes them from other seed plants.', '2700'),
(72, 'Biacroft Lab', 'biacroftlab@yopmail.com', 'Botany Cell Biology test', 'A large part of Cell Biology is the study of how biological molecules (mainly proteins and nucleic acids like DNA) account for the structure and function of cells.', '2300'),
(73, 'Flores Lab', 'floreslab@yopmail.com', 'Seeds Purity Test', 'This test is useful in determining the physical purity of seed. A composite sample which is true representative of a seed lot is used for seed testing purpose. From the composite sample, a small sample known as working sample (generally 25 g) is drawn for testing purpose. International Seed Testing Association (ISTA) rules are adopted for seed testing.', '2900'),
(74, 'Flores Lab', 'floreslab@yopmail.com', 'Leaves Testing', 'Iodine solution is used to test leaves for the presence of starch. Add the leaf to boiling ethanol in a water bath for a few minutes (the boiling ethanol dissolves the chlorophyll and removes the green colour from the leaf - it turns white so it is easy to see the change in colour).', '2700'),
(75, 'Flores Lab', 'floreslab@yopmail.com', 'Flowers Testing', 'The flowering plants (also called angiosperms) are the dominant and most familiar group of land plants. The flowering plants and the gymnosperms comprise the two groups in the seed plants. The flowers of flowering plants are the most remarkable feature that distinguishes them from other seed plants.', '2800'),
(76, 'Flores Lab', 'floreslab@yopmail.com', 'Botany Cell Biology test', 'A large part of Cell Biology is the study of how biological molecules (mainly proteins and nucleic acids like DNA) account for the structure and function of cells.', '2400'),
(77, 'Botany Zone', 'botanyzonelab@yopmail.com', 'Seeds Purity Test', 'This test is useful in determining the physical purity of seed. A composite sample which is true representative of a seed lot is used for seed testing purpose. From the composite sample, a small sample known as working sample (generally 25 g) is drawn for testing purpose. International Seed Testing Association (ISTA) rules are adopted for seed testing.', '3000'),
(78, 'Botany Zone', 'botanyzonelab@yopmail.com', 'Leaves Testing', 'Iodine solution is used to test leaves for the presence of starch. Add the leaf to boiling ethanol in a water bath for a few minutes (the boiling ethanol dissolves the chlorophyll and removes the green colour from the leaf - it turns white so it is easy to see the change in colour).', '2800'),
(79, 'Botany Zone', 'botanyzonelab@yopmail.com', 'Flowers Testing', 'The flowering plants (also called angiosperms) are the dominant and most familiar group of land plants. The flowering plants and the gymnosperms comprise the two groups in the seed plants. The flowers of flowering plants are the most remarkable feature that distinguishes them from other seed plants.', '2900'),
(80, 'Botany Zone', 'botanyzonelab@yopmail.com', 'Botany Cell Biology test', 'A large part of Cell Biology is the study of how biological molecules (mainly proteins and nucleic acids like DNA) account for the structure and function of cells.', '2500');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `test_details`
--
ALTER TABLE `test_details`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `test_details`
--
ALTER TABLE `test_details`
  MODIFY `id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
